language: generic

git:
  depth: 1

services:
  - docker

env:
  - DEPENDENCY_PACKAGES="libglib2.0-dev gobject-introspection libgtk-3-0 libgranite-dev libjson-glib-dev libsqlite3-dev libgee-0.8-dev meson valac"

install:
  - docker pull elementary/docker:odin-unstable
  - docker run -v "$PWD":/tmp/build-dir elementary/docker:odin-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build --prefix=/usr && cd build && ninja"

script:
  - echo BUILDS PASSED
